import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

const TRUSTED_TEST_PASSWORD =
  process.env.TRUSTED_TEST_PASSWORD ?? "integration-test-password";
process.env.TRUSTED_ACCESS_PASSWORD = TRUSTED_TEST_PASSWORD;
process.env.TRUSTED_SESSION_SECRET =
  process.env.TRUSTED_TEST_SESSION_SECRET ??
  "integration-test-session-secret-not-for-production";

let workerPromise;

async function getWorker() {
  if (!workerPromise) {
    const workerUrl = new URL("../dist/server/index.js", import.meta.url);
    workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
    workerPromise = import(workerUrl.href).then((module) => module.default);
  }
  return workerPromise;
}

async function render(path = "/") {
  return request(path, { headers: { accept: "text/html" } });
}

async function request(path, init = {}) {
  const worker = await getWorker();
  return worker.fetch(
    new Request(`http://localhost${path}`, init),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

function filesRecursively(directory, extension) {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return filesRecursively(path, extension);
    return path.endsWith(extension) ? [path] : [];
  });
}

function decodeSessionPayload(cookie) {
  const token = cookie.slice(cookie.indexOf("=") + 1);
  const encodedPayload = token.split(".", 1)[0];
  return JSON.parse(Buffer.from(encodedPayload, "base64url").toString("utf8"));
}

async function signedExpiredTrustedCookie() {
  const now = Math.floor(Date.now() / 1_000);
  const payload = Buffer.from(JSON.stringify({
    v: 1,
    iat: now - 28_801,
    exp: now - 1,
    nonce: "expired-session-test-nonce",
  })).toString("base64url");
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(process.env.TRUSTED_SESSION_SECRET),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const signature = Buffer.from(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(payload))).toString("base64url");
  return `__Host-jason_trusted_session=${payload}.${signature}`;
}

test("English is the canonical root experience", async () => {
  const response = await render("/");
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<html[^>]*lang="en"/i);
  assert.match(html, /<title>Jason Liao/i);
  assert.match(html, /From first principles to systems that/i);
  assert.match(html, /Download CV/i);
  assert.match(html, /hero__portrait-stage/);
  assert.match(html, /photo-01-a44ea8d43c/);
  assert.match(html, /hero__brand-seal/);
  assert.match(html, /hero__research-note/);
  assert.match(html, /NTU Academic Excellence Award/);
  assert.match(html, /I welcome inquiries about graduate study/);
  assert.doesNotMatch(html, /Dean(?:’|&rsquo;)s List/);
  assert.doesNotMatch(html, /react-loading-skeleton|Your site is taking shape/i);
  assert.doesNotMatch(html, /AI[- ]generated|generated by AI/i);
});

test("Traditional Chinese is a complete paired route", async () => {
  const response = await render("/zh");
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /<html[^>]*lang="zh-Hant"/i);
  assert.match(html, /我把數學與力學/i);
  assert.match(html, /下載 CV/i);
});

test("Explore and equal-probability Surprise Me remain available on every detail page", async () => {
  const routes = [
    "/projects/jarvis",
    "/academics/course-record",
    "/writing/autobiography/from-confusion-to-inner-coherence",
    "/zh/projects/jarvis",
    "/zh/academics/course-record",
    "/zh/writing/autobiography/from-confusion-to-inner-coherence",
  ];

  for (const route of routes) {
    const response = await render(route);
    assert.equal(response.status, 200, `Explorer detail route failed: ${route}`);
    const html = await response.text();
    assert.match(html, /guided-explorer-dock/);
    assert.match(html, /guided-explorer-surprise-trigger/);
    assert.match(html, /data-explorer-trigger/);
    assert.match(html, /data-surprise-trigger/);
    if (route.startsWith("/zh")) {
      assert.match(html, /隨機探索/);
    } else {
      assert.match(html, /Surprise me/);
    }
  }
});

test("academic evidence foregrounds Mechanical Engineering while retaining the full record", async () => {
  const home = await (await render("/")).text();
  const homeZh = await (await render("/zh")).text();
  const academics = await (await render("/academics")).text();
  const academicsZh = await (await render("/zh/academics")).text();
  const cv = await (await render("/cv")).text();
  const cvZh = await (await render("/zh/cv")).text();
  const record = await (await render("/experience/ntu-gpa-a-plus-record")).text();
  const recordZh = await (await render("/zh/experience/ntu-gpa-a-plus-record")).text();

  for (const html of [home, academics, cv, record]) {
    assert.match(html, /Mechanical Engineering Major GPA/);
    assert.match(html, /4\.19 \/ 4\.30/);
    assert.match(html, /3\.96 \/ 4\.00/);
    assert.match(html, /4\.13 \/ 4\.30/);
    assert.match(html, /3\.92 \/ 4\.00/);
    assert.match(html, /4\.21 \/ 4\.30/);
    assert.match(html, /3\.98 \/ 4\.00/);
    assert.match(html, /110 \/ 156|110 of 156/);
    assert.match(html, /50 credits/);
  }
  for (const html of [homeZh, academicsZh, cvZh, recordZh]) {
    assert.match(html, /機械工程(?:主修| Major) GPA/);
    assert.match(html, /4\.19／4\.30|4\.19 \/ 4\.30/);
    assert.match(html, /3\.96／4\.00|3\.96 \/ 4\.00/);
    assert.match(html, /4\.21／4\.30|4\.21 \/ 4\.30/);
    assert.match(html, /3\.98／4\.00|3\.98 \/ 4\.00/);
    assert.match(html, /4\.13／4\.30|4\.13 \/ 4\.30/);
    assert.match(html, /3\.92／4\.00|3\.92 \/ 4\.00/);
    assert.match(html, /110.*156|156.*110/);
    assert.match(html, /50 學分/);
    assert.match(html, /逐科(?:重算|換算)/);
  }

  const firstMajor = home.indexOf("4.19 / 4.30");
  const required = home.indexOf("4.21 / 4.30");
  const aPlus = home.indexOf("110 / 156");
  const overall = home.indexOf("4.13 / 4.30");
  assert.ok(firstMajor >= 0 && firstMajor < required && required < aPlus && aPlus < overall);
  assert.match(home, /99 graded credits/);
  assert.match(home, /70 graded credits/);
  assert.match(home, /not official NTU transcript fields/i);
  assert.match(home, /GPA calculations &amp; sources/);
  assert.match(home, /Required ME Coursework GPA/);
  assert.match(
    home,
    /<span>Academic recognition<\/span><strong>NTU Academic Excellence Award<\/strong>/,
  );
  assert.match(
    homeZh,
    /<span>學業榮譽<\/span><strong>臺大書卷獎<\/strong>/,
  );
  assert.doesNotMatch(home, /UC Berkeley ME major-GPA guidance/);
  assert.match(academics, /me\.berkeley\.edu\/graduate\/meng-admissions/);
  assert.match(academics, /International-GPA-Conversion\.pdf/);
  assert.match(academics, /cmc\.edu\/registrar\/calculating-major-gpa/);

  assert.match(academics, /id="academic-record"/);
  assert.match(academics, /UC Berkeley ME MEng admissions guidance/);
  assert.match(cv, /A concise two-page overview for academic and research applications/);
  assert.match(record, /GPA definitions and calculations/);
  assert.match(record, /Calculation method and references/);
  assert.match(record, /seven consecutive semester GPAs above 4\.00 \/ 4\.30/i);
  assert.match(recordZh, /GPA 採計範圍與換算結果/);
  assert.match(recordZh, /計算方法與參考依據/);
  assert.match(recordZh, /連續七學期的學期 GPA 均高於 4\.00／4\.30/);
  const contentModel = readFileSync(join(projectRoot, "lib", "content-data.ts"), "utf8");
  assert.match(contentModel, /Mechanical Engineering Major GPA is 4\.19 \/ 4\.30/);
  assert.match(contentModel, /Required Mechanical Engineering Coursework GPA is 4\.21 \/ 4\.30/);
  assert.match(contentModel, /依單科成績與實際學分計算/);
  assert.match(contentModel, /機械系定必修 GPA 為 4\.21／4\.30/);
  assert.doesNotMatch(`${home}${academics}${record}`, /official NTU (?:conversion|4\.0 GPA)/i);

  assert.match(home, /href="\/academics\/course-record"[^>]*>\s*View all courses &amp; grades/);
  assert.match(homeZh, /href="\/zh\/academics\/course-record"[^>]*>\s*查看全部課程與成績/);
  assert.match(home, /href="\/experience\/ntu-gpa-a-plus-record"[^>]*>\s*GPA calculations &amp; sources/);
  assert.match(homeZh, /href="\/zh\/experience\/ntu-gpa-a-plus-record"[^>]*>\s*GPA 採計與換算說明/);
  assert.doesNotMatch(record, /Appropriate use|When an application|reviewer explicitly/i);
  assert.doesNotMatch(recordZh, /適用情境|申請表|對方要求/);
  assert.doesNotMatch(`${home}${academics}`, /See the full academic record|查看完整學業紀錄|Browse the complete course record/);
});

test("legacy English routes redirect once to the unprefixed canonical route", async () => {
  const response = await render("/en/research?x=1");
  assert.equal(response.status, 301);
  const location = new URL(response.headers.get("location"), "http://localhost");
  assert.equal(`${location.pathname}${location.search}`, "/research?x=1");
});

test("coursework aliases redirect once to their canonical bilingual routes", async () => {
  const english = await render("/academics/coursework/physical-model-design-lab?from=video");
  const chinese = await render("/zh/academics/coursework/numerical-analysis");
  assert.equal(english.status, 301);
  assert.equal(chinese.status, 301);
  const englishLocation = new URL(english.headers.get("location"), "http://localhost");
  const chineseLocation = new URL(chinese.headers.get("location"), "http://localhost");
  assert.equal(`${englishLocation.pathname}${englishLocation.search}`, "/academics/coursework/physical-model-design-laboratory?from=video");
  assert.equal(chineseLocation.pathname, "/zh/academics/numerical-analysis");
});

test("all coursework detail routes render their complete bilingual public accounts", async () => {
  const records = JSON.parse(
    readFileSync(join(projectRoot, "lib", "coursework-public-details.json"), "utf8"),
  );
  assert.equal(records.length, 15);

  for (const record of records) {
    const english = await render(record.route);
    const chinese = await render(`/zh${record.route}`);
    assert.equal(english.status, 200, `English coursework route failed: ${record.route}`);
    assert.equal(chinese.status, 200, `Chinese coursework route failed: ${record.route}`);

    const englishHtml = await english.text();
    const chineseHtml = await chinese.text();
    assert.match(englishHtml, /id="complete-detail"/);
    assert.match(englishHtml, /Coursework details/);
    assert.match(englishHtml, /Methods, results, and reflection/);
    assert.match(chineseHtml, /id="complete-detail"/);
    assert.match(chineseHtml, /課程詳解/);
    assert.match(chineseHtml, /方法、結果與反思/);
  }
});

test("the complete course record renders bilingually and cross-links its academic context", async () => {
  const englishResponse = await render("/academics/course-record");
  const chineseResponse = await render("/zh/academics/course-record");
  assert.equal(englishResponse.status, 200);
  assert.equal(chineseResponse.status, 200);

  const english = await englishResponse.text();
  const chinese = await chineseResponse.text();
  assert.match(english, /<html[^>]*lang="en"/i);
  assert.match(chinese, /<html[^>]*lang="zh-Hant"/i);
  assert.match(english, /<meta property="og:locale" content="en_US"/);
  assert.match(english, /<meta property="og:locale:alternate" content="zh_TW"/);
  assert.match(chinese, /<meta property="og:locale" content="zh_TW"/);
  assert.match(chinese, /<meta property="og:locale:alternate" content="en_US"/);
  assert.match(english, /Complete Course &amp; Grade Record/);
  assert.match(english, /Courses and grades by semester/);
  assert.match(english, /Course-by-course record compiled from NTU academic records/);
  assert.match(chinese, /完整修課與成績紀錄/);
  assert.match(chinese, /八個學期的課程、學分與成績/);
  assert.match(chinese, /依臺大學業紀錄整理的修課與成績資料/);
  assert.doesNotMatch(english, /semester GPA/i);
  assert.doesNotMatch(chinese, /學期 GPA/);

  const strengthSection = english.slice(english.indexOf('id="record-highlights"'), english.indexOf('id="semester-record"'));
  const awardIndex = strengthSection.indexOf("NTU Academic Excellence Award");
  const majorIndex = strengthSection.indexOf("4.19 / 4.30");
  const aPlusIndex = strengthSection.indexOf("110 / 156");
  const coreIndex = strengthSection.indexOf("50 credits");
  const requiredIndex = strengthSection.indexOf("4.21 / 4.30");
  const overallIndex = strengthSection.indexOf("4.13 / 4.30");
  assert.ok(awardIndex >= 0 && awardIndex < majorIndex && majorIndex < aPlusIndex && aPlusIndex < coreIndex);
  assert.ok(coreIndex < requiredIndex && requiredIndex < overallIndex);

  for (const html of [english, chinese]) {
    const main = html.slice(html.indexOf("<main"), html.indexOf("</main>") + 7);
    const sectionMarkers = ['id="record-highlights"', 'id="semester-record"', 'id="capability-map"', 'id="record-method"'];
    const sectionPositions = sectionMarkers.map((marker) => main.indexOf(marker));
    assert.ok(sectionPositions.every((position) => position >= 0));
    assert.deepEqual([...sectionPositions].sort((a, b) => a - b), sectionPositions);
    const outlineStart = main.indexOf('class="landing-outline course-record-outline"');
    const outline = main.slice(outlineStart, main.indexOf("</nav>", outlineStart));
    const outlineMarkers = ['href="#record-highlights"', 'href="#semester-record"', 'href="#capability-map"', 'href="#record-method"'];
    const outlinePositions = outlineMarkers.map((marker) => outline.indexOf(marker));
    assert.ok(outlinePositions.every((position) => position >= 0));
    assert.deepEqual([...outlinePositions].sort((a, b) => a - b), outlinePositions);
    assert.doesNotMatch(outline, /href="#course-finder"/);
  }

  const englishMain = english.slice(english.indexOf("<main"), english.indexOf("</main>") + 7);
  const chineseMain = chinese.slice(chinese.indexOf("<main"), chinese.indexOf("</main>") + 7);
  const englishRecords = englishMain.match(/data-course-record(?:="(?:true)?")?/g) ?? [];
  const chineseRecords = chineseMain.match(/data-course-record(?:="(?:true)?")?/g) ?? [];
  assert.equal(englishRecords.length, 78);
  assert.equal(chineseRecords.length, 78);

  assert.match(english, /href="\/academics"/);
  assert.match(english, /href="\/experience\/ntu-gpa-a-plus-record"/);
  assert.match(chinese, /href="\/zh\/academics"/);
  assert.match(chinese, /href="\/zh\/experience\/ntu-gpa-a-plus-record"/);

  const academics = await (await render("/academics")).text();
  const academicsZh = await (await render("/zh/academics")).text();
  const gpaMethod = await (await render("/experience/ntu-gpa-a-plus-record")).text();
  const gpaMethodZh = await (await render("/zh/experience/ntu-gpa-a-plus-record")).text();
  assert.match(academics, /href="\/academics\/course-record"/);
  assert.match(academicsZh, /href="\/zh\/academics\/course-record"/);
  assert.match(gpaMethod, /href="\/academics\/course-record"/);
  assert.match(gpaMethodZh, /href="\/zh\/academics\/course-record"/);
});

test("the reconciled bilingual copy keeps the strongest current wording", async () => {
  const responses = await Promise.all([
    render("/academics/course-record"),
    render("/zh/academics/course-record"),
    render("/"),
    render("/writing"),
    render("/zh/writing"),
    render("/archive"),
    render("/zh/archive"),
    render("/writing/autobiography/from-confusion-to-inner-coherence"),
    render("/zh/writing/autobiography/from-confusion-to-inner-coherence"),
  ]);
  for (const response of responses) assert.equal(response.status, 200);

  const [courseEn, courseZh, homeEn, writingEn, writingZh, archiveEn, archiveZh, autobiographyEn, autobiographyZh] = await Promise.all(
    responses.map((response) => response.text()),
  );

  assert.match(courseEn, /Search the complete course record/);
  assert.match(courseZh, /查詢八學期修課紀錄/);
  assert.match(courseZh, /數學、力學、控制、設計與熱流領域的課程基礎/);
  assert.match(homeEn, /Video portfolio/);
  assert.match(writingEn, /Read both autobiographies in full/);
  assert.match(writingZh, /兩篇完整自傳/);
  assert.match(archiveEn, /full autobiographies/);
  assert.match(archiveZh, /篇自傳全文/);
  assert.match(autobiographyEn, /Full text/);
  assert.match(autobiographyZh, /全文/);

  const rendered = [courseEn, courseZh, homeEn, writingEn, writingZh, archiveEn, archiveZh, autobiographyEn, autobiographyZh].join("\n");
  assert.doesNotMatch(rendered, /Find a course across the complete record|查詢八學期完整修課紀錄|Project videos|unabridged essays|篇未刪節長文|Unabridged text/);

  const trustedSource = readFileSync(join(projectRoot, "components", "TrustedPage.tsx"), "utf8");
  assert.match(trustedSource, /english \? "Academic CV" : "學術履歷"/);
  assert.doesNotMatch(trustedSource, /Public academic CV|公開學術 CV/);
});

test("local-only events never receive a public route", async () => {
  const response = await render("/experience/portfolio-website-version-record");
  assert.equal(response.status, 404);
});

test("unknown routes return branded bilingual 404 pages", async () => {
  const english = await render("/not-a-real-portfolio-page");
  const chinese = await render("/zh/not-a-real-portfolio-page");
  assert.equal(english.status, 404);
  assert.equal(chinese.status, 404);
  assert.match(await english.text(), /The page may have moved or no longer exists/);
  assert.match(await chinese.text(), /你要查看的頁面可能已移動或不存在/);
});

test("visual records preserve real image proportions without boilerplate captions", async () => {
  const response = await render("/projects/aero-carrier");
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /gallery-item__media/);
  assert.match(html, /gallery-item--full/);
  assert.match(html, /width="2560" height="1920"/);
  assert.match(html, /Aero Carrier quadrotor prototype/);
  assert.doesNotMatch(html, /Authentic visual evidence included/i);
});

test("document metadata uses natural singular and plural page labels", async () => {
  const english = await render("/projects/jarvis");
  const chinese = await render("/zh/projects/jarvis");
  assert.equal(english.status, 200);
  assert.equal(chinese.status, 200);

  const englishHtml = await english.text();
  const chineseHtml = await chinese.text();
  assert.match(englishHtml, /1 page/);
  assert.doesNotMatch(englishHtml, /1 pages/);
  assert.match(chineseHtml, /1 頁/);
});

test("About portraits use a ratio-aware pair with readable bilingual captions", async () => {
  const english = await render("/about");
  const chinese = await render("/zh/about");
  assert.equal(english.status, 200);
  assert.equal(chinese.status, 200);

  const englishHtml = await english.text();
  const chineseHtml = await chinese.text();
  assert.match(englishHtml, /gallery-grid--balanced-pair/);
  assert.match(englishHtml, /--gallery-column-a:0\.563fr/);
  assert.match(englishHtml, /width="1440" height="2560"/);
  assert.match(englishHtml, /width="1290" height="1423"/);
  assert.match(englishHtml, /Beyond the classroom/);
  assert.match(englishHtml, /Personal photographs/);
  assert.match(englishHtml, /Jason Liao on a ski slope/);
  assert.match(englishHtml, /Jason Liao at an orchid exhibition/);
  assert.match(chineseHtml, /課堂之外/);
  assert.match(chineseHtml, /個人照片/);
  assert.match(chineseHtml, /雪地滑雪留影/);
  assert.match(chineseHtml, /蘭花展留影/);
  assert.doesNotMatch(`${englishHtml}${chineseHtml}`, /Project images|成果影像/);
  assert.doesNotMatch(`${englishHtml}${chineseHtml}`, /Authentic visual evidence included|作為真實成果與過程紀錄/i);
});

test("Academic honors labels the grade image as an academic record", async () => {
  const english = await render("/academics/honors");
  const chinese = await render("/zh/academics/honors");
  assert.equal(english.status, 200);
  assert.equal(chinese.status, 200);

  const englishHtml = await english.text();
  const chineseHtml = await chinese.text();
  assert.match(englishHtml, /Academic record/);
  assert.match(englishHtml, /Spring 2026 course results/);
  assert.match(chineseHtml, /學業紀錄/);
  assert.match(chineseHtml, /114-2 學期成績紀錄/);
  assert.doesNotMatch(`${englishHtml}${chineseHtml}`, /Project images|成果影像/);
  assert.doesNotMatch(englishHtml, /href="\/experience\/ntu-gpa-a-plus-record"/);
  assert.doesNotMatch(chineseHtml, /href="\/zh\/experience\/ntu-gpa-a-plus-record"/);
});

test("Contact quick paths keep titles and descriptions in one stable row unit", async () => {
  const english = await render("/contact");
  const chinese = await render("/zh/contact");
  assert.equal(english.status, 200);
  assert.equal(chinese.status, 200);

  const englishHtml = await english.text();
  const chineseHtml = await chinese.text();
  assert.match(englishHtml, /contact-quick-panel/);
  assert.match(englishHtml, /contact-quick-row__copy[^>]*><strong>Research<\/strong><small>RedRHex and geometry<\/small>/);
  assert.match(englishHtml, /contact-quick-row__copy[^>]*><strong>Projects<\/strong><small>Engineering projects and prototypes<\/small>/);
  assert.match(chineseHtml, /contact-quick-row__copy[^>]*><strong>研究<\/strong><small>RedRHex 與幾何研究<\/small>/);
  assert.match(chineseHtml, /aria-label="建議先查看的頁面"/);
});

test("primary landing pages use real visual entries without duplicate entity links", async () => {
  for (const path of ["/research", "/projects", "/academics", "/leadership", "/zh/research", "/zh/projects", "/zh/academics", "/zh/leadership"]) {
    const response = await render(path);
    assert.equal(response.status, 200);
    const html = await response.text();
    assert.match(html, /section--featured-index/);
    assert.match(html, /case-card__media/);
    assert.match(html, /class="landing-outline"/);
    assert.match(html, /id="all-records"/);
    assert.doesNotMatch(html, /class="archive-list"/);
  }

  const projects = await (await render("/projects")).text();
  assert.equal((projects.match(/href="\/projects\/aero-carrier"/g) ?? []).length, 1);
  assert.equal((projects.match(/href="\/projects\/jarvis"/g) ?? []).length, 1);
  assert.match(projects, /photo-01-20d6cdcccd/);
  assert.match(projects, /photo-04-0ea165d340/);
});

test("content-led landing pages place documented work before explanatory summaries", async () => {
  for (const path of [
    "/research",
    "/projects",
    "/academics",
    "/leadership",
    "/writing",
    "/academics/honors",
    "/writing/teaching",
    "/updates",
    "/zh/research",
    "/zh/projects",
    "/zh/academics",
    "/zh/leadership",
    "/zh/writing",
    "/zh/academics/honors",
    "/zh/writing/teaching",
    "/zh/updates",
  ]) {
    const html = await (await render(path)).text();
    const main = html.slice(html.indexOf("<main"), html.indexOf("</main>") + 7);
    const records = main.indexOf('id="all-records"');
    const overview = main.indexOf('id="page-overview"');
    assert.ok(records >= 0, `${path} should expose its documented collection`);
    assert.ok(overview < 0 || records < overview, `${path} should place documented work before its overview`);

    const recordsLink = main.indexOf('href="#all-records"');
    const overviewLink = main.indexOf('href="#page-overview"');
    assert.ok(recordsLink >= 0, `${path} should link to its documented collection`);
    assert.ok(overviewLink < 0 || recordsLink < overviewLink, `${path} outline should mirror the content order`);
  }
});

test("projects present every project before the optional comparison workspace", async () => {
  for (const path of ["/projects", "/zh/projects"]) {
    const html = await (await render(path)).text();
    const main = html.slice(html.indexOf("<main"), html.indexOf("</main>") + 7);
    const markers = ['id="selected-work"', 'id="all-records"', 'id="page-overview"', 'id="project-comparison"'];
    const positions = markers.map((marker) => main.indexOf(marker));
    assert.ok(positions.every((position) => position >= 0), `${path} should render every project section`);
    assert.deepEqual([...positions].sort((a, b) => a - b), positions, `${path} project sections should remain evidence-first`);

    const outlineMarkers = ['href="#selected-work"', 'href="#all-records"', 'href="#page-overview"', 'href="#project-comparison"'];
    const outlinePositions = outlineMarkers.map((marker) => main.indexOf(marker));
    assert.ok(outlinePositions.every((position) => position >= 0));
    assert.deepEqual([...outlinePositions].sort((a, b) => a - b), outlinePositions, `${path} outline should mirror the project sections`);
  }
});

test("landing collections use purpose-built groups without losing university-first chronology", async () => {
  for (const path of ["/leadership", "/zh/leadership"]) {
    const response = await render(path);
    assert.equal(response.status, 200);
    const html = await response.text();
    assert.match(html, /class="landing-collection-groups"/);
    assert.match(html, /id="collection-current"/);
    assert.match(html, path.startsWith("/zh") ? /大學階段與近期成果/ : /Current and university work/);
    const currentIndex = html.indexOf('id="collection-current"');
    const highSchoolIndex = html.indexOf('id="collection-high-school"');
    assert.ok(currentIndex >= 0);
    assert.ok(highSchoolIndex < 0 || currentIndex < highSchoolIndex);
  }

  for (const path of ["/academics", "/zh/academics"]) {
    const html = await (await render(path)).text();
    const prefix = path.startsWith("/zh") ? "/zh" : "";
    const ids = [
      "collection-academic-record",
      "collection-mathematics",
      "collection-mechanics-control",
      "collection-computation-experiments",
      "collection-design-manufacturing",
      "collection-honors",
    ];
    const positions = ids.map((id) => html.indexOf(`id="${id}"`));
    assert.ok(positions.every((position) => position >= 0));
    assert.deepEqual(positions, [...positions].sort((a, b) => a - b));
    assert.match(html, path.startsWith("/zh") ? /依學術領域瀏覽/ : /Browse by academic domain/);
    assert.doesNotMatch(html, /id="collection-additional"/);
    const courseworkRecords = JSON.parse(
      readFileSync(join(projectRoot, "lib", "coursework-public-details.json"), "utf8"),
    );
    for (const record of courseworkRecords) {
      assert.equal(
        (html.match(new RegExp(`href="${prefix}${record.route.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}"`, "g")) ?? []).length,
        1,
        `Expected one Academics entry for ${prefix}${record.route}`,
      );
    }
  }

  for (const path of ["/writing", "/zh/writing"]) {
    const html = await (await render(path)).text();
    assert.match(html, path.startsWith("/zh") ? /自傳全文/ : /Autobiographies/);
    assert.match(html, /id="collection-technical-research"/);
    assert.match(html, /id="collection-teaching-communication"/);
    assert.doesNotMatch(html, /id="collection-additional"/);
  }
});

test("About, Personal, and Writing expose distinct, low-friction entry paths", async () => {
  const checks = [
    ["/about", "/writing", "Read the complete autobiographies"],
    ["/personal", "/about", "View the professional overview"],
    ["/writing", "/about", "View the professional overview"],
    ["/zh/about", "/zh/writing", "閱讀兩篇完整自傳"],
    ["/zh/personal", "/zh/about", "查看專業簡介"],
    ["/zh/writing", "/zh/about", "查看專業簡介"],
  ];

  for (const [path, route, label] of checks) {
    const html = await (await render(path)).text();
    assert.match(html, new RegExp(`href="${route}"[^>]*>${label}`));
  }

  for (const path of ["/about", "/zh/about"]) {
    const html = await (await render(path)).text();
    const prefix = path.startsWith("/zh") ? "/zh" : "";
    for (const route of [
      "/experience/ntu-academic-journey",
      "/experience/ntu-mechanical-engineering",
      "/experience/ntu-mathematics-minor",
    ]) assert.match(html, new RegExp(`href="${prefix}${route}"`));
    assert.match(html, path.startsWith("/zh") ? /學術歷程/ : /Academic path/);
  }
});

test("detail pages introduce full-proportion media early and distribute it through the narrative", async () => {
  const english = await (await render("/research/redrhex")).text();
  const chinese = await (await render("/zh/research/redrhex")).text();

  const heroIndex = english.indexOf("case-hero-media");
  const firstSectionIndex = english.indexOf('id="thesis"');
  const firstVideoIndex = english.indexOf('id="demonstration"');
  const secondSectionIndex = english.indexOf('id="question-constraints"');
  assert.ok(heroIndex > 0 && heroIndex < firstSectionIndex);
  assert.ok(firstVideoIndex > firstSectionIndex && firstVideoIndex < secondSectionIndex);
  assert.match(english, /class="page-breadcrumb"/);
  assert.match(english, /"@type":"BreadcrumbList"/);
  assert.match(english, /media-lightbox__trigger/);
  assert.match(english, /gallery-grid--narrative/);
  assert.match(chinese, /figure-01-6d30d97b35/);
  assert.equal((english.match(/figure-01-6d30d97b35\.webp/g) ?? []).length >= 1, true);
});

test("detail pages return to their collection and preserve one authored next-best step", async () => {
  for (const path of ["/projects/aero-carrier", "/zh/projects/aero-carrier"]) {
    const html = await (await render(path)).text();
    assert.match(html, path.startsWith("/zh") ? /href="\/zh\/projects"[^>]*>[^<]*<svg[^>]*>[\s\S]*?回到工程專案|回到工程專案/ : /Back to Projects/);
    const sectionStart = html.indexOf(path.startsWith("/zh") ? "延伸閱讀" : "Related work");
    assert.ok(sectionStart > 0);
    const section = html.slice(sectionStart, html.indexOf("</main>", sectionStart));
    assert.match(section, path.startsWith("/zh") ? /繼續閱讀/ : /View related work/);
    assert.match(section, new RegExp(`href="${path.startsWith("/zh") ? "/zh" : ""}/academics/coursework/practice-of-mechanical-engineering"`));
    assert.doesNotMatch(section, new RegExp(`href="${path.startsWith("/zh") ? "/zh" : ""}/projects"`));
  }
});

test("portfolio collections foreground university work before high-school foundations", async () => {
  const checks = [
    ["/academics", "/academics/coursework/additive-manufacturing", "/experience/chien-kuo-mathematics-competition"],
    ["/leadership", "/experience/ntu-bicycle-service-week", "/experience/trml-captain-2020-2021"],
    ["/research", "/experience/joining-ntu-biorola", "/research/geometry-covering"],
    ["/personal", "/experience/ntu-civil-night-vocalist", "/experience/chien-kuo-chorus-best-soloist"],
  ];

  for (const [path, universityRoute, highSchoolRoute] of checks) {
    for (const localePrefix of ["", "/zh"]) {
      const response = await render(`${localePrefix}${path}`);
      assert.equal(response.status, 200);
      const html = await response.text();
      const universityHref = `href="${localePrefix}${universityRoute}"`;
      const highSchoolHref = `href="${localePrefix}${highSchoolRoute}"`;
      const universityIndex = html.indexOf(universityHref);
      const highSchoolIndex = html.indexOf(highSchoolHref);
      assert.ok(universityIndex >= 0, `Missing ${universityHref}`);
      assert.ok(highSchoolIndex >= 0, `Missing ${highSchoolHref}`);
      assert.ok(
        universityIndex < highSchoolIndex,
        `${universityRoute} must precede ${highSchoolRoute} on ${localePrefix}${path}`,
      );
    }
  }
});

test("the retired mechanics midterm item is absent from routes, indexes, and sitemap", async () => {
  for (const path of [
    "/experience/mechanics-of-materials-midterm-101",
    "/zh/experience/mechanics-of-materials-midterm-101",
  ]) {
    assert.equal((await render(path)).status, 404);
  }

  for (const path of ["/", "/zh", "/academics", "/zh/academics", "/sitemap.xml"]) {
    const response = await render(path);
    assert.equal(response.status, 200);
    const body = await response.text();
    assert.doesNotMatch(body, /mechanics-of-materials-midterm-101/i);
    assert.doesNotMatch(body, /Mechanics of Materials Midterm|材料力學期中考 101/i);
  }
});

test("both autobiographies are complete standalone bilingual reading pages", async () => {
  const articles = [
    {
      route: "/writing/autobiography/from-confusion-to-inner-coherence",
      count: 69,
      titleEn: /From Losing My Way to Finding Inner Coherence/,
      titleZh: /從迷惘到自洽/,
      openingZh: /大四某個深夜，實驗室裡只剩電腦風扇/,
      endingZh: /我就知道，自己沒有走丟。/,
    },
    {
      route: "/writing/autobiography/gewu-xiangzhe-preface",
      count: 58,
      titleEn: /Gewu Xiangzhe: The One Who Investigates Things and Soars — A Self-Preface/,
      titleZh: /《格物翔者·自序》/,
      openingZh: /「格致」出自《大學》/,
      endingZh: /不負所學，不負少年，不負星河。/,
    },
  ];

  for (const article of articles) {
    const english = await render(article.route);
    const chinese = await render(`/zh${article.route}`);
    assert.equal(english.status, 200);
    assert.equal(chinese.status, 200);

    const englishHtml = await english.text();
    const chineseHtml = await chinese.text();
    assert.match(englishHtml, /longform-page/);
    assert.match(chineseHtml, /longform-page/);
    assert.match(englishHtml, article.titleEn);
    assert.match(chineseHtml, article.titleZh);
    assert.match(chineseHtml, article.openingZh);
    assert.match(chineseHtml, article.endingZh);
    const expectedIndices = Array.from({ length: article.count }, (_, index) => index + 1);
    const englishIndices = [...englishHtml.matchAll(/data-source-index="(\d+)"/g)].map((match) => Number(match[1]));
    const chineseIndices = [...chineseHtml.matchAll(/data-source-index="(\d+)"/g)].map((match) => Number(match[1]));
    assert.deepEqual(englishIndices, expectedIndices);
    assert.deepEqual(chineseIndices, expectedIndices);
    assert.match(englishHtml, new RegExp(`href="/zh${article.route.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}"`));
    assert.doesNotMatch(`${englishHtml}${chineseHtml}`, /\.docx\b/i);
  }

  for (const path of ["/writing", "/zh/writing", "/about", "/zh/about"]) {
    const response = await render(path);
    assert.equal(response.status, 200);
    const html = await response.text();
    assert.match(html, /autobiography\/from-confusion-to-inner-coherence/);
    assert.match(html, /autobiography\/gewu-xiangzhe-preface/);
  }
});

test("the complete index contains every public record once in university-first order", async () => {
  for (const path of ["/archive", "/zh/archive"]) {
    const response = await render(path);
    assert.equal(response.status, 200);
    const html = await response.text();
    const ids = [...html.matchAll(/data-archive-entity="([^"]+)"/g)].map((match) => match[1]);
    assert.equal(ids.length, 75);
    assert.equal(new Set(ids).size, 75);
    assert.match(html, /figure-01-46f68dba79/);
    assert.match(html, /id="archive-all"/);
    assert.match(html, /href="#archive-all"/);
    assert.match(html, path.startsWith("/zh") ? /aria-label="依內容類型快速前往"/ : /aria-label="Jump to a record type"/);
    assert.match(html, /id="archive-kind-university-research"/);
    assert.match(html, /id="archive-kind-university-coursework"/);
    assert.match(html, /id="archive-kind-university-writing"/);
    assert.match(html, /class="archive-hero__primary-link" href="#archive-all"/);
    assert.ok(html.indexOf('id="archive-all"') < html.indexOf('id="portfolio-constellation"'));
    const prefix = path.startsWith("/zh") ? "/zh" : "";
    assert.ok(html.indexOf(`href="${prefix}/projects/jarvis"`) < html.indexOf(`href="${prefix}/experience/trml-captain-2020-2021"`));
    assert.ok(html.indexOf(`href="${prefix}/experience/trml-captain-2020-2021"`) < html.indexOf(`href="${prefix}/experience/tmt8-2018"`));
  }
});

test("honors and teaching collections are complete bilingual routes", async () => {
  for (const path of ["/academics/honors", "/zh/academics/honors", "/writing/teaching", "/zh/writing/teaching"]) {
    const response = await render(path);
    assert.equal(response.status, 200);
    const html = await response.text();
    assert.match(html, /section--featured-index|visual-index-grid/);
    assert.doesNotMatch(html, /class="not-found"/);
  }
});

test("teaching and communication stays focused on instruction and outreach", async () => {
  for (const path of ["/writing/teaching", "/zh/writing/teaching"]) {
    const html = await (await render(path)).text();
    const start = html.indexOf('id="all-records"');
    const collection = html.slice(start, html.indexOf("</main>", start));
    assert.match(collection, /ntu-peer-review-sessions/);
    assert.match(collection, /chien-kuo-science-club-teaching/);
    assert.match(collection, /taylor-series-video/);
    assert.match(collection, /mathematical-popular-writing-2021/);
    assert.doesNotMatch(collection, /autobiography\/from-confusion-to-inner-coherence/);
    assert.doesNotMatch(collection, /international-student-document-support/);
    assert.doesNotMatch(collection, /ntu-bicycle-service-week/);
    assert.doesNotMatch(collection, /mathematica-curvilinear-basis/);
  }
});

test("experience breadcrumbs lead to the most relevant subject collection", async () => {
  const expectations = [
    ["/experience/ntu-gpa-a-plus-record", "/academics/course-record"],
    ["/experience/ntu-academic-excellence-award", "/academics/honors"],
    ["/experience/trml-captain-2020-2021", "/leadership"],
    ["/experience/ntu-civil-night-vocalist", "/personal"],
    ["/experience/joining-ntu-biorola", "/research"],
    ["/experience/ntu-academic-journey", "/about"],
  ];

  for (const [route, parent] of expectations) {
    for (const prefix of ["", "/zh"]) {
      const html = await (await render(`${prefix}${route}`)).text();
      const breadcrumb = html.match(/<nav class="page-breadcrumb"[\s\S]*?<\/nav>/)?.[0] ?? "";
      assert.match(breadcrumb, new RegExp(`href="${prefix}${parent.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}"`));
    }
  }
});

test("updates presents curated milestones in a meaningful recent-first order", async () => {
  for (const path of ["/updates", "/zh/updates"]) {
    const html = await (await render(path)).text();
    const start = html.indexOf('id="all-records"');
    const index = html.slice(start, html.indexOf("</main>", start));
    const prefix = path.startsWith("/zh") ? "/zh" : "";
    const positions = [
      "/projects/jarvis",
      "/experience/ntu-gpa-a-plus-record",
      "/projects/aero-carrier",
      "/research/redrhex",
      "/experience/joining-ntu-biorola",
      "/projects/lkas",
    ].map((route) => index.indexOf(`href="${prefix}${route}"`));
    assert.ok(positions.every((position) => position >= 0));
    assert.deepEqual(positions, [...positions].sort((a, b) => a - b));
    assert.doesNotMatch(index, /autobiography\/from-confusion-to-inner-coherence/);
  }
});

test("Jarvis presents the technical demo and behind-the-build documentary in both languages", async () => {
  for (const path of ["/projects/jarvis", "/zh/projects/jarvis"]) {
    const response = await render(path);
    assert.equal(response.status, 200);
    const html = await response.text();
    assert.match(html, /2qIh_a8zVKs/);
    assert.match(html, /WKsGbI2Ig1k/);
    assert.match(html, path.startsWith("/zh") ? /MakeNTU 2026 參賽全紀錄｜36 小時打造 Jarvis/ : /Behind the Build: Jarvis at MakeNTU 2026/);
    assert.match(html, path.startsWith("/zh") ? /參賽全紀錄/ : /Project documentary/);
    assert.doesNotMatch(html, /<iframe\b/i);
    assert.equal((html.match(/"@type":"VideoObject"/g) ?? []).length, 2);
    assert.match(html, /"duration":"PT9M27S"/);
  }
});

test("all non-case public events have complete bilingual visitor-safe detail copy", async () => {
  const details = JSON.parse(
    readFileSync(join(projectRoot, "lib", "event-public-details.json"), "utf8"),
  );
  assert.equal(details.length, 51);
  assert.equal(new Set(details.map((record) => record.eventId)).size, 51);
  assert.equal(new Set(details.map((record) => record.route)).size, 51);
  assert.equal(
    details.filter((record) => record.sourceStatus === "canonical_markdown").length,
    51,
  );
  assert.equal(
    details.some((record) => !record.blocks.en.length || !record.blocks.zh.length),
    false,
  );

  const serialized = JSON.stringify(details);
  assert.doesNotMatch(
    serialized,
    /Internal Editorial Notes|Do Not Publish|內部建站註記|禁止直接公開|canonical_source|local_only|[A-Za-z]:\\\\Users\\\\/i,
  );

  const completedSources = [
    ["/writing/mathematica-curvilinear-basis", /Turning a derivation into checkable symbolic computation/, /把推導變成可重複檢查的符號計算/],
    ["/experience/cross-cultural-taiwan-exchange", /From formal support to mutual exchange/, /從協助新生，到彼此交流/],
    ["/experience/ef-tokyo-study-abroad", /Putting language into everyday life in Tokyo/, /在東京，把語言放進日常生活/],
    ["/experience/premier12-2024-fan-memory", /Sharing Team Taiwan(?:&#x27;|')s championship moment/, /與中華隊共同經歷的冠軍時刻/],
    ["/experience/class-discipline-officer", /Everyday responsibility and teamwork/, /日常責任與團隊合作/],
    ["/writing/teaching/taylor-series-video", /A 25-minute, 18-second online lesson on Taylor series/, /25 分 18 秒的泰勒展開式線上教學/],
    ["/writing/mathematical-popular-writing-2021", /From countability to Cantor(?:&#x27;|')s diagonal argument/, /從可數到 Cantor 對角線/],
    ["/experience/central-emergency-operations-center-visit", /Connecting civil engineering to public systems/, /從防災體系理解土木工程的公共責任/],
  ];

  for (const [route, englishCopy, chineseCopy] of completedSources) {
    const english = await render(route);
    const chinese = await render(`/zh${route}`);
    assert.equal(english.status, 200, `English event detail failed: ${route}`);
    assert.equal(chinese.status, 200, `Chinese event detail failed: /zh${route}`);
    const englishHtml = await english.text();
    const chineseHtml = await chinese.text();
    assert.match(englishHtml, /id="complete-detail"/);
    assert.match(chineseHtml, /id="complete-detail"/);
    assert.match(englishHtml, englishCopy);
    assert.match(chineseHtml, chineseCopy);
    assert.doesNotMatch(
      `${englishHtml}${chineseHtml}`,
      /Internal Editorial Notes|Do Not Publish|內部建站註記|禁止直接公開|canonical_source|local_only|[A-Za-z]:\\\\Users\\\\/i,
    );
  }
});

test("metadata, case normalization, and experience aliases resolve cleanly", async () => {
  const research = await render("/research");
  const researchHtml = await research.text();
  assert.match(researchHtml, /<title>Research — Jason Liao<\/title>/);
  assert.doesNotMatch(researchHtml, /Jason Liao — Jason Liao/);
  assert.match(researchHtml, /<link rel="canonical" href="https:\/\/jason-liao-academic-portfolio\.jasonliaock26\.chatgpt\.site\/research"/);
  assert.doesNotMatch(researchHtml, /(?:canonical|hreflang|og:url)[^>]*localhost/i);

  const redrhexHtml = await (await render("/research/redrhex")).text();
  const redrhexOgImage = redrhexHtml.match(/<meta property="og:image" content="([^"]+)"/)?.[1] ?? "";
  assert.match(redrhexOgImage, /\/assets\/images\/research\/redrhex\//);
  assert.doesNotMatch(redrhexOgImage, /\/og\.png$/);
  assert.match(redrhexHtml, /"@type":"ImageObject"/);
  assert.match(redrhexHtml, /"@type":"VideoObject"/);
  assert.match(redrhexHtml, /"@type":"DigitalDocument"/);
  assert.doesNotMatch(redrhexHtml, /"@type":"Report"/);
  assert.match(redrhexHtml, /"duration":"PT44S"/);
  assert.match(redrhexHtml, /"uploadDate":"2026-08-10T14:46:10-07:00"/);
  assert.match(redrhexHtml, /<title>RedRHex Locomotion Control — Jason Liao<\/title>/);

  const conciseMetadataTitles = new Map([
    ["/writing/autobiography/gewu-xiangzhe-preface", "Gewu Xiangzhe: A Self-Preface"],
    ["/projects/polar-arm", "Mechanical Polar-Coordinate Transport Arm"],
    ["/experience/chien-kuo-gifted-class", "Chien Kuo Mathematics &amp; Science Gifted Class"],
    ["/writing/mathematica-curvilinear-basis", "Curvilinear Basis Differentiation in Mathematica"],
    ["/experience/chien-kuo-mathematics-competition", "Chien Kuo Mathematics Competition Awards"],
    ["/experience/chien-kuo-overseas-program-planning", "Chien Kuo Overseas Program Planning Lead"],
    ["/experience/chien-kuo-research-presentation-lead", "Chien Kuo Research Symposium Coordinator"],
    ["/experience/baseball-fandom", "Baseball: Team Taiwan, CTBC &amp; Yankees"],
    ["/experience/apx-2021", "2021 APX Mathematics Awards"],
    ["/writing/teaching/taylor-series-video", "Taylor-Series Science Club Lesson"],
    ["/writing/mathematical-popular-writing-2021", "Popular Mathematics Writing (2021)"],
  ]);
  for (const [route, expectedTitle] of conciseMetadataTitles) {
    const html = await (await render(route)).text();
    assert.ok(
      html.includes(`<title>${expectedTitle} — Jason Liao</title>`),
      `Unexpected metadata title for ${route}`,
    );
  }

  const uppercase = await render("/Research?view=all");
  assert.equal(uppercase.status, 301);
  assert.equal(new URL(uppercase.headers.get("location"), "http://localhost").pathname, "/research");

  const experience = await render("/experience?from=archive");
  const chineseExperience = await render("/zh/experience?from=archive");
  assert.equal(experience.status, 301);
  assert.equal(chineseExperience.status, 301);
  assert.equal(new URL(experience.headers.get("location"), "http://localhost").pathname, "/updates");
  assert.equal(new URL(chineseExperience.headers.get("location"), "http://localhost").pathname, "/zh/updates");
});

test("keyboard navigation preserves focus across skip links, mobile menus, and image dialogs", () => {
  const navigation = readFileSync(join(projectRoot, "components", "Navigation.tsx"), "utf8");
  const skipLink = readFileSync(join(projectRoot, "components", "SkipLink.tsx"), "utf8");
  const lightbox = readFileSync(join(projectRoot, "components", "MediaLightbox.tsx"), "utf8");
  const mainComponents = ["HomePage.tsx", "PageView.tsx", "PortfolioArchivePage.tsx", "AutobiographyPage.tsx", "TrustedPage.tsx"]
    .map((file) => readFileSync(join(projectRoot, "components", file), "utf8"))
    .join("\n");
  assert.match(navigation, /<SkipLink locale=\{locale\}/);
  assert.match(skipLink, /href="#main-content"/);
  assert.match(mainComponents, /id="main-content"[^>]*tabIndex=\{-1\}/);
  assert.match(navigation, /event\.key === "Escape" && open/);
  assert.match(navigation, /closeMenu\(true\)/);
  assert.match(navigation, /addEventListener\("focusout"/);
  assert.match(navigation, /trapMenuButtonFocus/);
  assert.match(lightbox, /trapDialogFocus/);
  assert.match(lightbox, /handleBackdropClick/);
  assert.match(lightbox, /closeButtonRef\.current\?\.focus/);
});

test("Chinese presentation labels remain Chinese", async () => {
  const academics = await (await render("/zh/academics")).text();
  const home = await (await render("/zh")).text();
  assert.match(academics, /數學與計算|力學與動力學/);
  assert.doesNotMatch(academics, />Mathematics &amp; Computation</);
  assert.match(home, /已驗證|依報告記載/);
  assert.doesNotMatch(home, />verified<|>reported</);
  assert.doesNotMatch(`${academics}${home}`, /層級 [SABC]|Tier [SABC]/);
});

test("the homepage presents verified outcomes before interactive synthesis and extended navigation", async () => {
  for (const path of ["/", "/zh"]) {
    const response = await render(path);
    assert.equal(response.status, 200);
    const html = await response.text();
    const markers = [
      'id="home-academic-record"',
      'id="home-current-research"',
      'id="home-selected-systems"',
      'id="home-academic-work"',
      'id="home-capability-summary"',
      'id="home-capability-atlas"',
      'id="portfolio-cinema"',
      'id="home-trajectory"',
      'id="home-leadership"',
      'id="home-portfolio-map"',
    ];
    const positions = markers.map((marker) => html.indexOf(marker));
    assert.ok(positions.every((position) => position >= 0));
    assert.deepEqual(positions, [...positions].sort((left, right) => left - right));
    assert.doesNotMatch(html, /id="home-recent-work"/);

    assert.equal((html.match(/class="portfolio-trajectory__period"/g) ?? []).length, 5);
    assert.equal((html.match(/class="portfolio-trajectory__entry"/g) ?? []).length, 21);
    assert.match(
      html,
      path === "/zh"
        ? /數學基礎逐步成形[\s\S]*從競賽走向研究、教學與帶隊[\s\S]*在臺大重建跨域基礎[\s\S]*讓模型進入實體系統[\s\S]*研究、整合與實作成果/
        : /Mathematical foundations take shape[\s\S]*From competition to inquiry, teaching, and leadership[\s\S]*Rebuilding an interdisciplinary foundation at NTU[\s\S]*Taking models into physical systems[\s\S]*Research, integration, and tested systems/,
    );
    const prefix = path === "/zh" ? "/zh" : "";
    for (const route of [
      "/experience/mathleague-2016",
      "/research/geometry-covering",
      "/experience/ntu-mechanical-engineering",
      "/projects/inventor-system-integration",
      "/research/redrhex",
      "/projects/jarvis",
    ]) assert.match(html, new RegExp(`href="${prefix}${route}"`));
  }
});

test("every sitemap route and every approved public asset resolves", async () => {
  const sitemap = await render("/sitemap.xml");
  assert.equal(sitemap.status, 200);
  const xml = await sitemap.text();
  const paths = [...xml.matchAll(/<loc>https?:\/\/[^/]+([^<]*)<\/loc>/g)].map((match) => match[1] || "/");
  assert.equal(paths.length, 180);
  for (const path of paths) {
    const response = await render(path);
    assert.equal(response.status, 200, `Sitemap route failed: ${path}`);
    const html = await response.text();
    assert.doesNotMatch(
      html,
      /Appropriate use|適用情境|Why this record remains|為什麼保留這段紀錄|The boundary of the public account|公開敘事的界線|belongs within the complete learning trajectory|適合放在完整學習脈絡|not presented as personal credit|review room|審閱室|tailored packet|one source of truth|source paragraph slots|Follow the evidence|Open this evidence|Documented connections|linked portfolio evidence|Public edition for online review|Complete public record|every public entry|Curated paths|The page count is not the point|這項活動不需要寫成宏大的領導故事|原始資料顯示正式名稱|可交付的錄影版本|完成交付|這段作品讓人看見|找到直覺入口|三項主幹|模型資產|開始查找|雙語敘事|唯一 KPI|網站不需要|網站標示為|不需要在研究型首頁|不應與研究成果爭奪首頁|側視圖圖|Your site is taking shape|Under construction/i,
      `Public-facing editorial or build language leaked into ${path}`,
    );
  }

  const manifest = JSON.parse(readFileSync(join(projectRoot, "lib", "media-manifest.json"), "utf8"));
  assert.equal(manifest.length, 117);
  assert.doesNotMatch(
    JSON.stringify(manifest),
    /Authentic visual evidence included|Full PDF available for inline review|local deployment paths removed|Public Academic CV 2026-08|24-Slide Public Edition|enterprise-award|Research-presentation website responsibility map/i,
  );
  assert.equal(manifest.filter((asset) => asset.kind === "image").length, 73);
  assert.equal(manifest.filter((asset) => asset.kind === "document").length, 44);

  const expectedNewDocuments = new Map([
    ["doc-intermediate-dynamics-complete-exam", ["/academics/intermediate-dynamics", "/documents/intermediate-dynamics-complete-final-exam-and-solutions-2026.pdf", 52, "public_original"]],
    ["doc-python-library-escape-presentation", ["/academics/coursework/computer-programming-in-python", "/documents/python-library-escape-reinforcement-learning-project-presentation-2026.pdf", 20, "public_derivative_metadata_scrubbed"]],
    ["doc-physical-model-presentation", ["/academics/coursework/physical-model-design-laboratory", "/documents/plant-inspired-3d-marble-run-physical-model-presentation-2026.pdf", 38, "public_derivative_metadata_scrubbed"]],
    ["doc-inventor-system-integration-presentation", ["/projects/inventor-system-integration", "/documents/inventor-ball-circulation-system-integration-presentation-2025.pdf", 24, "public_derivative_metadata_scrubbed"]],
    ["doc-research-presentation-plan", ["/experience/chien-kuo-research-presentation-lead", "/documents/chien-kuo-independent-research-symposium-plan-2021.pdf", 5, "public_derivative_metadata_scrubbed"]],
    ["doc-apmo-participation-redacted", ["/experience/apmoc-apmo-tmo-selection", "/documents/apmo-2020-participation-certificate-redacted.pdf", 1, "public_redacted_derivative_metadata_scrubbed"]],
    ["doc-chien-kuo-diploma-redacted", ["/experience/chien-kuo-gifted-class", "/documents/chien-kuo-high-school-diploma-redacted.pdf", 2, "public_redacted_derivative_metadata_scrubbed"]],
    ["doc-chien-kuo-gifted-certificates-redacted", ["/experience/chien-kuo-gifted-class", "/documents/chien-kuo-gifted-program-certificates-redacted.pdf", 2, "public_redacted_derivative_metadata_scrubbed"]],
  ]);
  for (const [id, [route, publicPath, pageCount, status]] of expectedNewDocuments) {
    const asset = manifest.find((entry) => entry.id === id);
    assert.ok(asset, `Missing newly authorized public document: ${id}`);
    assert.equal(asset.route, route);
    assert.equal(asset.publicPath, publicPath);
    assert.equal(asset.pageCount, pageCount);
    assert.equal(asset.status, status);
    assert.equal(asset.rights, "user_confirmed_public");
    assert.equal(asset.metadataScrubbed, true);
    assert.equal(asset.download, true);
  }

  const approvedRedactedSourceHashes = new Map([
    ["doc-apmo-participation-redacted", "5D0B15FA2F0D03F06EEE6093091DA6BE08C1536557F66B829D9BDA1CE4FBA164"],
    ["doc-chien-kuo-gifted-certificates-redacted", "557E9319B33FF9EFF1DB41577E422C7703AA31000E233AB04126614966657634"],
    ["doc-chien-kuo-diploma-redacted", "2560F237F85B8E43633F44072CD957FD5A34CA26D6F92332F6AFC7114B0895A1"],
  ]);
  for (const [id, sourceSha256] of approvedRedactedSourceHashes) {
    const asset = manifest.find((entry) => entry.id === id);
    assert.equal(asset.sourceSha256, sourceSha256);
    assert.equal(asset.sourceOriginalDeployed, false);
  }

  assert.deepEqual(
    manifest.filter((asset) => asset.kind === "document" && asset.route === "/academics/intermediate-dynamics").map((asset) => asset.id),
    ["doc-intermediate-dynamics-final", "doc-intermediate-dynamics-complete-exam"],
  );
  assert.deepEqual(
    manifest.filter((asset) => asset.kind === "document" && asset.route === "/experience/chien-kuo-gifted-class").map((asset) => asset.id),
    ["doc-chien-kuo-gifted-certificates-redacted", "doc-chien-kuo-diploma-redacted"],
  );
  assert.deepEqual(
    manifest.filter((asset) => asset.kind === "document" && asset.route === "/experience/chien-kuo-research-presentation-lead").map((asset) => asset.id),
    ["doc-research-presentation-plan", "doc-research-presentation-introduction", "doc-research-presentation-poster"],
  );

  const expectedPrimaryDocuments = new Map([
    ["/academics/intermediate-dynamics", ["doc-intermediate-dynamics-final", "/documents/intermediate-dynamics-final-project-2026.pdf"]],
    ["/academics/numerical-analysis", ["doc-numerical-analysis-final", "/documents/numerical-analysis-final-project-2026.pdf"]],
    ["/experience/chien-kuo-gifted-class", ["doc-chien-kuo-gifted-certificates-redacted", "/documents/chien-kuo-gifted-program-certificates-redacted.pdf"]],
    ["/experience/chien-kuo-mathematics-competition", ["doc-math-competition-2019", "/documents/chien-kuo-mathematics-competition-second-prize-2019.pdf"]],
    ["/experience/chien-kuo-science-club-teaching", ["doc-teaching-calculus", "/documents/calculus-teaching-notes.pdf"]],
    ["/experience/rongshu-cup-2019-2020", ["doc-rongshu-cup-2019", "/documents/rongshu-cup-honorable-mention-2019.pdf"]],
    ["/experience/trml-captain-2020-2021", ["doc-trml-2020-taipei", "/documents/trml-2020-taipei-team-second-prize.pdf"]],
    ["/projects/aero-carrier", ["doc-aero-carrier-final", "/documents/aero-carrier-final-report-2026.pdf"]],
    ["/research/redrhex", ["doc-redrhex-final", "/documents/redrhex-research-report-2026.pdf"]],
    ["/research/geometry-covering", ["doc-geometry-covering-full", "/documents/geometry-covering-optimization-complete-work-36-pages-2021.pdf"]],
    ["/projects/jarvis", ["doc-jarvis-presentation", "/documents/jarvis-multimodal-home-hub-presentation-2026.pdf"]],
    ["/projects/lkas", ["doc-lkas-final", "/documents/lkas-vehicle-dynamics-control-final-report-2025.pdf"]],
    ["/experience/chien-kuo-research-presentation-lead", ["doc-research-presentation-plan", "/documents/chien-kuo-independent-research-symposium-plan-2021.pdf"]],
  ]);
  for (const [route, [id, href]] of expectedPrimaryDocuments) {
    assert.equal(
      manifest.find((asset) => asset.kind === "document" && asset.route === route)?.id,
      id,
      `Unexpected primary document for ${route}`,
    );
    const html = await (await render(route)).text();
    assert.match(html, new RegExp(`<a class="button" href="${href.replaceAll("/", "\\/")}[^>]*>.*?Open full document`, "s"));
  }

  const intermediateHtml = await (await render("/academics/intermediate-dynamics")).text();
  assert.match(intermediateHtml, /<a class="button" href="\/documents\/intermediate-dynamics-final-project-2026\.pdf"[^>]*>.*?Open full document/s);
  const giftedHtml = await (await render("/experience/chien-kuo-gifted-class")).text();
  assert.match(giftedHtml, /<a class="button" href="\/documents\/chien-kuo-gifted-program-certificates-redacted\.pdf"[^>]*>.*?Open full document/s);
  const presentationHtml = await (await render("/experience/chien-kuo-research-presentation-lead")).text();
  assert.match(presentationHtml, /<a class="button" href="\/documents\/chien-kuo-independent-research-symposium-plan-2021\.pdf"[^>]*>.*?Open full document/s);

  for (const asset of manifest) {
    for (const publicPath of [asset.publicPath, asset.previewPath, asset.variants?.avif?.publicPath, asset.variants?.webp?.publicPath, asset.variants?.fallback?.publicPath].filter(Boolean)) {
      assert.equal(existsSync(join(projectRoot, "public", publicPath.replace(/^\//, ""))), true, `Missing public asset: ${publicPath}`);
    }
  }
});

test("protected contact details stay out of anonymous pages and client bundles", async () => {
  const privateNeedles = [
    "+886 903 202 825",
    "886903202825",
    "github.com/JasonLiaoJCS",
    "facebook.com/share/18Jxkq87b4",
    "instagram.com/jason.liao_ck326",
    "linkedin.com/in/chih-hsiang-jason-liao",
    "jasonliao-pages.pages.dev",
  ];

  for (const route of ["/", "/zh", "/contact", "/zh/contact", "/trusted", "/zh/trusted"]) {
    const response = await render(route);
    assert.equal(response.status, 200, `Anonymous contact surface failed: ${route}`);
    const html = await response.text();
    for (const needle of privateNeedles) {
      assert.equal(html.includes(needle), false, `Anonymous ${route} leaked ${needle}`);
    }
  }

  const homeHtml = await (await render("/")).text();
  const contactHtml = await (await render("/contact")).text();
  assert.match(homeHtml, /jasonliaohyh9815@gmail\.com/i);
  assert.match(contactHtml, /jasonliaohyh9815@gmail\.com/i);
  assert.match(contactHtml, /Professional contact card/i);
  assert.match(contactHtml, /Checking access/i);
  assert.match(
    readFileSync(join(projectRoot, "components", "ElectronicContactCard.tsx"), "utf8"),
    /Sign in to view the full card/i,
  );

  const clientDirectory = join(projectRoot, "dist", "client");
  for (const file of filesRecursively(clientDirectory, ".js")) {
    const source = readFileSync(file, "utf8");
    for (const needle of privateNeedles) {
      assert.equal(source.includes(needle), false, `Client bundle leaked ${needle}: ${file}`);
    }
  }

  const privateModuleConsumers = [];
  for (const root of ["app", "components", "lib", "worker"]) {
    for (const extension of [".ts", ".tsx"]) {
      for (const file of filesRecursively(join(projectRoot, root), extension)) {
        if (file.endsWith("private-contact-profile.ts")) continue;
        if (readFileSync(file, "utf8").includes("private-contact-profile")) {
          privateModuleConsumers.push(file.replaceAll("\\", "/"));
        }
      }
    }
  }
  assert.equal(privateModuleConsumers.length, 3);
  assert.ok(privateModuleConsumers.every((file) => file.includes("/app/api/trusted/contact-card/")));
});

test("trusted access is server-verified, persistent, and safely cleared", async () => {
  const anonymous = await render("/trusted");
  assert.equal(anonymous.status, 200);
  assert.match(anonymous.headers.get("cache-control") ?? "", /no-store/i);
  assert.match(anonymous.headers.get("x-robots-tag") ?? "", /noindex/i);
  const anonymousHtml = await anonymous.text();
  assert.match(anonymousHtml, />Continue</i);
  assert.match(anonymousHtml, /type="password"/i);
  assert.match(anonymousHtml, /method="post"/i);
  assert.match(anonymousHtml, /action="\/api\/trusted\/login"/i);
  assert.doesNotMatch(anonymousHtml, /Access granted/i);
  assert.doesNotMatch(anonymousHtml, /class="not-found"/i);

  for (const endpoint of [
    "/api/trusted/contact-card",
    "/api/trusted/contact-card/vcard",
    "/api/trusted/contact-card/qr",
  ]) {
    const response = await request(endpoint, { headers: { accept: "*/*" } });
    assert.equal(response.status, 401, `Anonymous access was not rejected: ${endpoint}`);
    assert.match(response.headers.get("cache-control") ?? "", /no-store/i);
    assert.match(response.headers.get("x-robots-tag") ?? "", /noindex/i);
    assert.equal(response.headers.get("x-content-type-options"), "nosniff");
    assert.ok(
      (response.headers.get("vary") ?? "")
        .split(",")
        .map((value) => value.trim())
        .includes("Cookie"),
    );
    assert.equal(response.headers.get("cross-origin-resource-policy"), "same-origin");
    const body = await response.text();
    assert.doesNotMatch(body, /886903202825|JasonLiaoJCS|jason\.liao_ck326|chih-hsiang-jason-liao|jasonliao-pages/i);
  }

  const commonHeaders = {
    accept: "application/json",
    "content-type": "application/json",
    origin: "http://localhost",
    "sec-fetch-site": "same-origin",
    "user-agent": "trusted-integration-test",
  };

  const rejectedOrigin = await request("/api/trusted/login", {
    method: "POST",
    headers: { ...commonHeaders, origin: "https://example.invalid", "sec-fetch-site": "cross-site" },
    body: JSON.stringify({ password: TRUSTED_TEST_PASSWORD }),
  });
  assert.equal(rejectedOrigin.status, 403);
  assert.equal(rejectedOrigin.headers.get("set-cookie"), null);

  const rejectedPassword = await request("/api/trusted/login", {
    method: "POST",
    headers: commonHeaders,
    body: JSON.stringify({ password: "definitely-not-the-password" }),
  });
  assert.equal(rejectedPassword.status, 401);
  assert.equal(rejectedPassword.headers.get("set-cookie"), null);

  const login = await request("/api/trusted/login", {
    method: "POST",
    headers: commonHeaders,
    body: JSON.stringify({ password: TRUSTED_TEST_PASSWORD }),
  });
  assert.equal(login.status, 200);
  const setCookie = login.headers.get("set-cookie") ?? "";
  assert.match(setCookie, /__Host-jason_trusted_session=/);
  assert.match(setCookie, /HttpOnly/i);
  assert.match(setCookie, /Secure/i);
  assert.match(setCookie, /SameSite=Lax/i);
  assert.match(setCookie, /Path=\//i);
  assert.match(setCookie, /Max-Age=28800/i);
  assert.doesNotMatch(setCookie, /Domain=/i);
  const cookie = setCookie.split(";", 1)[0];
  const sessionPayload = decodeSessionPayload(cookie);
  assert.equal(sessionPayload.exp - sessionPayload.iat, 28_800);

  const authorized = await request("/trusted", {
    headers: { accept: "text/html", cookie },
  });
  assert.equal(authorized.status, 200);
  const authorizedHtml = await authorized.text();
  assert.match(authorizedHtml, /Access granted/i);
  assert.match(authorizedHtml, /Selected materials/i);
  assert.match(authorizedHtml, /Academic profile at a glance/i);
  assert.match(authorizedHtml, /Mechanical Engineering Major GPA/);
  assert.match(authorizedHtml, /4\.19 \/ 4\.30/);
  assert.match(authorizedHtml, /3\.96 \/ 4\.00/);
  assert.match(authorizedHtml, /4\.13 \/ 4\.30/);
  assert.match(authorizedHtml, /not (?:an? )?official NTU transcript (?:value|field)/i);
  assert.doesNotMatch(authorizedHtml, /type="password"/i);

  const contactResponse = await request("/api/trusted/contact-card", {
    headers: { accept: "application/json", cookie },
  });
  assert.equal(contactResponse.status, 200);
  assert.equal(contactResponse.headers.get("set-cookie"), null);
  assert.match(contactResponse.headers.get("cache-control") ?? "", /no-store/i);
  assert.ok(
    (contactResponse.headers.get("vary") ?? "")
      .split(",")
      .map((value) => value.trim())
      .includes("Cookie"),
  );
  assert.equal(contactResponse.headers.get("cross-origin-resource-policy"), "same-origin");
  const contact = await contactResponse.json();
  assert.equal(contact.authorized, true);
  assert.equal(contact.profile.name, "Chih-Hsiang (Jason) Liao");
  assert.equal(contact.profile.nameZh, "廖致翔");
  assert.equal(contact.profile.phone.display, "+886 903 202 825");
  assert.equal(contact.profile.phone.href, "tel:+886903202825");
  assert.equal(contact.profile.email, "jasonliaohyh9815@gmail.com");
  assert.ok(contact.expiresAt > Date.now());
  assert.ok(contact.expiresAt <= Date.now() + 28_800_000);
  assert.deepEqual(contact.profile.networks.map((network) => network.id), ["github", "linkedin", "instagram", "facebook", "website"]);

  const vCardResponse = await request("/api/trusted/contact-card/vcard", {
    headers: { accept: "text/vcard", cookie },
  });
  assert.equal(vCardResponse.status, 200);
  assert.equal(vCardResponse.headers.get("set-cookie"), null);
  assert.match(vCardResponse.headers.get("content-type") ?? "", /^text\/vcard/i);
  assert.match(vCardResponse.headers.get("content-disposition") ?? "", /attachment; filename="Chih-Hsiang-Jason-Liao\.vcf"/i);
  assert.equal(vCardResponse.headers.get("cross-origin-resource-policy"), "same-origin");
  const vCard = await vCardResponse.text();
  assert.ok(vCard.startsWith("BEGIN:VCARD\r\nVERSION:3.0\r\n"));
  assert.ok(
    vCard
      .split("\r\n")
      .filter(Boolean)
      .every((line) => Buffer.byteLength(line, "utf8") <= 75),
  );
  assert.match(vCard, /\r\n /);
  assert.match(vCard, /FN:Chih-Hsiang \(Jason\) Liao\r\n/);
  assert.match(vCard, /TEL;TYPE=CELL,VOICE:\+886903202825\r\n/);
  assert.match(vCard, /X-SOCIALPROFILE;TYPE=linkedin:/i);
  assert.ok(vCard.endsWith("END:VCARD\r\n"));

  const qrResponse = await request("/api/trusted/contact-card/qr", {
    headers: { accept: "image/svg+xml", cookie },
  });
  assert.equal(qrResponse.status, 200);
  assert.equal(qrResponse.headers.get("set-cookie"), null);
  assert.match(qrResponse.headers.get("content-type") ?? "", /^image\/svg\+xml/i);
  assert.equal(qrResponse.headers.get("cross-origin-resource-policy"), "same-origin");
  const qr = await qrResponse.text();
  assert.match(qr, /<svg[^>]+viewBox=/i);
  assert.ok(qr.length > 1_000);

  const expiredCookie = await signedExpiredTrustedCookie();
  for (const endpoint of [
    "/api/trusted/contact-card",
    "/api/trusted/contact-card/vcard",
    "/api/trusted/contact-card/qr",
  ]) {
    const response = await request(endpoint, { headers: { cookie: expiredCookie } });
    assert.equal(response.status, 401, `Expired session reached ${endpoint}`);
  }

  const refreshed = await request("/trusted", {
    headers: { accept: "text/html", cookie },
  });
  assert.match(await refreshed.text(), /Access granted/i);

  const cookieSeparator = cookie.indexOf("=");
  const cookieName = cookie.slice(0, cookieSeparator);
  const [payload, signature] = cookie.slice(cookieSeparator + 1).split(".");
  const forgedSignature = `${signature[0] === "a" ? "b" : "a"}${signature.slice(1)}`;
  const forged = `${cookieName}=${payload}.${forgedSignature}`;
  const forgedSession = await request("/trusted", {
    headers: { accept: "text/html", cookie: forged },
  });
  const forgedHtml = await forgedSession.text();
  assert.match(forgedHtml, />Continue</i);
  assert.doesNotMatch(forgedHtml, /Access granted/i);

  const formLogin = await request("/api/trusted/login", {
    method: "POST",
    redirect: "manual",
    headers: {
      "content-type": "application/x-www-form-urlencoded",
      origin: "http://localhost",
      "sec-fetch-site": "same-origin",
      "user-agent": "trusted-form-fallback-test",
    },
    body: new URLSearchParams({
      password: TRUSTED_TEST_PASSWORD,
      redirectTo: "/zh/trusted",
    }).toString(),
  });
  assert.equal(formLogin.status, 303);
  assert.equal(formLogin.headers.get("location"), "/zh/trusted");
  assert.match(formLogin.headers.get("set-cookie") ?? "", /HttpOnly/i);

  const logout = await request("/api/trusted/logout", {
    method: "POST",
    headers: {
      origin: "http://localhost",
      "sec-fetch-site": "same-origin",
      "user-agent": "trusted-integration-test",
    },
  });
  assert.equal(logout.status, 200);
  const clearedCookie = logout.headers.get("set-cookie") ?? "";
  assert.match(clearedCookie, /Max-Age=0/i);
  assert.match(clearedCookie, /HttpOnly/i);
  assert.match(clearedCookie, /Secure/i);

  const afterLogout = await render("/trusted");
  assert.match(await afterLogout.text(), />Continue</i);
});
