export type GewuPrefaceParagraph = {
  sourceIndex: number;
  kind: "title" | "byline" | "section" | "paragraph" | "spacer";
  zh: string;
  en: string;
};

export const gewuXiangzhePreface = {
  id: "autobiography-gewu-xiangzhe-preface",
  canonicalRoute: "/writing/autobiography/gewu-xiangzhe-preface",
  title: {
    zh: "《格物翔者·自序》",
    en: "Gewu Xiangzhe: The One Who Investigates Things and Soars — A Self-Preface",
  },
  paragraphs: ([
    {
      sourceIndex: 0,
      kind: "title",
      zh: "《格物翔者·自序》",
      en: "Gewu Xiangzhe: The One Who Investigates Things and Soars — A Self-Preface",
    },
    { sourceIndex: 1, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 2,
      kind: "byline",
      zh: "廖致翔，字格致，自號格物翔者",
      en: "Chih-Hsiang Liao—courtesy name Gezhi, with the chosen sobriquet Gewu Xiangzhe, ‘one who investigates things and soars.’",
    },
    { sourceIndex: 3, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 4,
      kind: "section",
      zh: "1.字：",
      en: "1. Courtesy Name:",
    },
    { sourceIndex: 5, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 6,
      kind: "paragraph",
      zh: "「格致」出自《大學》：「欲誠其意者，先致其知；致知在格物。」朱熹曰：「格物，窮理也；致知，極知也。」",
      en: "‘Gezhi’ comes from The Great Learning: ‘Those who wish to make their intentions sincere must first extend their knowledge; the extension of knowledge lies in the investigation of things.’ Zhu Xi wrote: ‘To investigate things is to exhaust their principles; to extend knowledge is to carry knowing to its utmost.’",
    },
    {
      sourceIndex: 7,
      kind: "paragraph",
      zh: "格物以窮理，致知以盡心。",
      en: "Investigate things to fathom principle; extend knowledge to fully realize the heart-mind.",
    },
    { sourceIndex: 8, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 9,
      kind: "paragraph",
      zh: "此二字，正是我自期，亦為我治學、做研究之本心。",
      en: "These two characters express what I ask of myself; they are the guiding conviction behind my study and research.",
    },
    {
      sourceIndex: 10,
      kind: "paragraph",
      zh: "我不甘於死記成句，學必探其本源；",
      en: "I cannot content myself with memorizing finished phrases; whatever I learn, I must trace to its source;",
    },
    {
      sourceIndex: 11,
      kind: "paragraph",
      zh: "不惟求「理解」，更是要求「凡所學皆能說服自己，無疑於心」。",
      en: "I seek not merely to ‘understand,’ but to reach the point where ‘everything I learn is sufficient to convince me, leaving no doubt within my heart.’",
    },
    { sourceIndex: 12, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 13,
      kind: "paragraph",
      zh: "「格致學」乃物理學舊譯，而物理本以觀察、實驗、推論窮究萬物之理。我所學，皆循此道而行；每一次推導、每一個實驗，皆是身體力行「致知在格物」。",
      en: "‘Gezhi learning’ was an early Chinese name for physics, and physics itself seeks, through observation, experiment, and inference, to plumb the principles of all things. Everything I study follows this path; each derivation and every experiment is an embodied practice of the teaching that ‘the extension of knowledge lies in the investigation of things.’",
    },
    { sourceIndex: 14, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 15,
      kind: "paragraph",
      zh: "本名「致翔」，寓致力飛翔之志；",
      en: "My given name, Chih-Hsiang (致翔), holds the aspiration to devote myself to soaring;",
    },
    {
      sourceIndex: 16,
      kind: "paragraph",
      zh: "字取「格致」，為致力窮理之功。",
      en: "my courtesy name, Gezhi (格致), names the discipline of devoting myself to the search for principle.",
    },
    { sourceIndex: 17, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 18,
      kind: "paragraph",
      zh: "致翔者，志向也；格致者，工夫也。",
      en: "Chih-Hsiang names the aspiration; Gezhi names the disciplined practice.",
    },
    {
      sourceIndex: 19,
      kind: "paragraph",
      zh: "志不立，則翔不高；理不明，則翼不穩。",
      en: "Without a settled purpose, one cannot soar high; without principles made clear, one’s wings cannot hold steady.",
    },
    {
      sourceIndex: 20,
      kind: "paragraph",
      zh: "——以格致為翼，方能致翔於天。",
      en: "—Only with Gezhi as my wings can I, Chih-Hsiang, soar into the heavens.",
    },
    { sourceIndex: 21, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 22,
      kind: "paragraph",
      zh: "《大學》又曰：「致知在格物，物格而後知至，知至而後意誠，意誠而後心正，心正而後身修，身修而後家齊，家齊而後國治，國治而後天下平。」",
      en: "The Great Learning also says: ‘Knowledge is extended through the investigation of things. Only after things are investigated does knowledge become complete; only after knowledge is complete are intentions sincere; only after intentions are sincere is the mind set right; only after the mind is set right is the person cultivated; only after the person is cultivated is the family ordered; only after the family is ordered is the state well governed; only after the state is well governed is there peace under Heaven.’",
    },
    {
      sourceIndex: 23,
      kind: "paragraph",
      zh: "於是我悟到，所謂「格物」，不獨格「物理」之理，亦在格「人心」之情。",
      en: "I came to understand, then, that gewu is not only to investigate the li—the principles—of the physical world, but also to discern the qing—the feelings—of the human heart.",
    },
    { sourceIndex: 24, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 25,
      kind: "paragraph",
      zh: "格物以知事，格人以知心；",
      en: "Examine things to understand affairs; seek to understand people to know the heart;",
    },
    {
      sourceIndex: 26,
      kind: "paragraph",
      zh: "求真不失溫度，講理不忘人情。",
      en: "pursue truth without losing warmth; speak from reason without forgetting human feeling.",
    },
    {
      sourceIndex: 27,
      kind: "paragraph",
      zh: "我願在求知、逐夢、交友之間，",
      en: "In seeking knowledge, pursuing dreams, and building friendships,",
    },
    {
      sourceIndex: 28,
      kind: "paragraph",
      zh: "用同一份真誠去走完我人生的道路。",
      en: "I hope to walk the whole road of my life with the same undivided sincerity.",
    },
    { sourceIndex: 29, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 30,
      kind: "section",
      zh: "2.自號",
      en: "2. Self-Chosen Sobriquet",
    },
    { sourceIndex: 31, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 32,
      kind: "paragraph",
      zh: "此四字為號，亦是自許。",
      en: "These four characters are my sobriquet, and also the promise I make to myself.",
    },
    { sourceIndex: 33, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 34,
      kind: "paragraph",
      zh: "我之所愛，不過三事：知識、自由、棒球。",
      en: "I love but three things: knowledge, freedom, and baseball.",
    },
    {
      sourceIndex: 35,
      kind: "paragraph",
      zh: "我的人生，一半時間在方程矩陣間穿梭，一半則是在球場吶喊。二者看似殊途，其實同源——",
      en: "I spend half my life threading my way through equations and matrices, and the other half shouting from the ballfield. The two may seem to follow different roads, yet they spring from the same source—",
    },
    {
      sourceIndex: 36,
      kind: "paragraph",
      zh: "理性為骨，熱血為心。",
      en: "Reason in my bones; passion in my heart.",
    },
    { sourceIndex: 37, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 38,
      kind: "paragraph",
      zh: "「格物」是看世界的方法：",
      en: "‘Gewu’—the investigation of things—is how I look upon the world:",
    },
    {
      sourceIndex: 39,
      kind: "paragraph",
      zh: "遇事先問「何以然」，再論「當如何」；",
      en: "when something arises, first ask, ‘Why is it so?’ and only then, ‘What ought to be done?’;",
    },
    {
      sourceIndex: 40,
      kind: "paragraph",
      zh: "先明道理，再計得失；",
      en: "first make the principle clear, then weigh gain and loss;",
    },
    {
      sourceIndex: 41,
      kind: "paragraph",
      zh: "先立是非，再論成敗。",
      en: "first discern right from wrong, then speak of success or failure.",
    },
    { sourceIndex: 42, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 43,
      kind: "paragraph",
      zh: "「翔者」是我行世之姿。",
      en: "‘Xiangzhe’—the one who soars—is the bearing with which I move through the world.",
    },
    {
      sourceIndex: 44,
      kind: "paragraph",
      zh: "名中有「翔」，號亦取「翔」，自為照映。於我而言：",
      en: "My name carries the character 翔, ‘to soar,’ and my sobriquet takes it up again; the two reflect one another. To me:",
    },
    { sourceIndex: 45, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 46,
      kind: "paragraph",
      zh: "翔，不是離地，而是在踏實行走中，仍不忘仰望長空。",
      en: "To soar is not to leave the earth; it is to walk upon it with steady feet and still remember to lift one’s eyes to the boundless sky.",
    },
    {
      sourceIndex: 47,
      kind: "paragraph",
      zh: "自許心境如天之高遠，待人如天之寬容，行事如天之剛健。",
      en: "I ask of myself a mind as lofty as the sky, a forbearance toward others as vast as the sky, and a steadfast vigor in action like that of the sky.",
    },
    { sourceIndex: 48, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 49,
      kind: "paragraph",
      zh: "故以此自勉：",
      en: "Thus I set these words before myself:",
    },
    { sourceIndex: 50, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 51,
      kind: "paragraph",
      zh: "以格物觀世事，以翔者立其志；",
      en: "with gewu, behold the affairs of the world; as one who soars, establish my aspiration;",
    },
    {
      sourceIndex: 52,
      kind: "paragraph",
      zh: "心居學問之中，眼向蒼穹之上。",
      en: "let the heart dwell within learning, while the eyes turn upward to the vault of heaven.",
    },
    { sourceIndex: 53, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 54,
      kind: "paragraph",
      zh: "我，廖致翔，字格致，號格物翔者，願此一生——",
      en: "I, Chih-Hsiang Liao—courtesy name Gezhi, with the chosen sobriquet Gewu Xiangzhe—wish to spend this life—",
    },
    { sourceIndex: 55, kind: "spacer", zh: "", en: "" },
    {
      sourceIndex: 56,
      kind: "paragraph",
      zh: "以理立身，以熱血行路；",
      en: "to found my life on reason, and walk my road with a fervent heart;",
    },
    {
      sourceIndex: 57,
      kind: "paragraph",
      zh: "不負所學，不負少年，不負星河。",
      en: "to be worthy of what I have learned, worthy of my youth, and worthy of the river of stars.",
    },
  ] satisfies GewuPrefaceParagraph[]).map((paragraph, index) => ({
    ...paragraph,
    sourceIndex: index + 1,
  })),
} as const;
